name: Container Security Scan (OSCAR)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      IMAGE_REF: ghcr.io/grycap/oscar:3.6.2
      SBOM_FILE: sbom-oscar-cyclonedx.json
      TRIVY_TABLE: trivy-table.txt
      TRIVY_SARIF: trivy-results.sarif
      GRYPE_TABLE: grype-table.txt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Instalar Trivy ---
      - name: Set up Trivy
        uses: aquasecurity/setup-trivy@v0.1.5

      # --- Generar SBOM con Trivy ---
      - name: Generate SBOM (CycloneDX JSON)
        run: |
          trivy image --format cyclonedx --output "$SBOM_FILE" "$IMAGE_REF"

      # --- Escaneo con Trivy en tabla ---
      - name: Trivy scan (table)
        run: |
          trivy image --format table --output "$TRIVY_TABLE" "$IMAGE_REF" || true

      # --- Escaneo con Trivy en SARIF (para CodeQL/Security) ---
      - name: Trivy scan (SARIF)
        run: |
          trivy image --format sarif --output "$TRIVY_SARIF" "$IMAGE_REF" || true

      # --- Instalar Grype ---
      - name: Install Grype
        uses: anchore/scan-action/download-grype@v3
        with:
          version: v0.69.0

      # --- Validación de SBOM (CycloneDX esperado) ---
      - name: Assert SBOM is CycloneDX
        shell: bash
        run: |
          echo "Primeras líneas del SBOM:"
          head -n 5 "$SBOM_FILE" || true
          if command -v jq >/dev/null 2>&1; then
            bf=$(jq -r '.bomFormat // empty' "$SBOM_FILE" || true)
            echo "bomFormat detectado: $bf"
            if [ "$bf" != "CycloneDX" ]; then
              echo "WARNING: El SBOM no parece CycloneDX; grype podría fallar."
            fi
          fi

      # --- Escaneo con Grype desde SBOM con fallback ---
      - name: Grype scan (table from SBOM, with fallback)
        shell: bash
        run: |
          set -o pipefail
          echo "== Ejecutando Grype sobre SBOM =="
          if grype "sbom:${SBOM_FILE}" -o table --add-cpes-if-none 2>&1 | tee "$GRYPE_TABLE" ; then
            echo "Grype SBOM OK"
          else
            echo "Grype SBOM falló; intentando fallback sobre la imagen..." | tee -a "$GRYPE_TABLE"
            grype "${IMAGE_REF}" -o table --add-cpes-if-none 2>&1 | tee -a "$GRYPE_TABLE" || true
          fi

          if [ ! -s "$GRYPE_TABLE" ]; then
            echo "NOTE: grype no produjo salida (revisa SBOM o DB). Dump de versión:" > "$GRYPE_TABLE"
            grype version 2>&1 | tee -a "$GRYPE_TABLE" || true
          fi

      # --- Subir reportes como artifacts ---
      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: oscar-security-reports
          path: |
            ${{ env.SBOM_FILE }}
            ${{ env.TRIVY_TABLE }}
            ${{ env.TRIVY_SARIF }}
            ${{ env.GRYPE_TABLE }}
