- name: Trivy scan (table)
  uses: aquasecurity/trivy-action@0.28.0
  with:
    image-ref: ${{ env.IMAGE_REF }}
    format: table
    exit-code: 0
    severity: CRITICAL,HIGH
  continue-on-error: true

- name: Trivy scan (SARIF)
  uses: aquasecurity/trivy-action@0.28.0
  with:
    image-ref: ${{ env.IMAGE_REF }}
    format: sarif
    output: ${{ env.TRIVY_SARIF }}
  continue-on-error: true
