name: Container Security Scan (OSCAR)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Trivy
        uses: aquasecurity/setup-trivy@v0.2.2

      - name: Run Trivy image scan
        run: |
          trivy image --exit-code 0 --format table ghcr.io/grycap/oscar:3.6.2
          trivy image --exit-code 1 --severity HIGH,CRITICAL --format sarif -o trivy-results.sarif ghcr.io/grycap/oscar:3.6.2

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif

      - name: Run Syft to generate SBOM
        uses: anchore/sbom-action@v0.17.3
        with:
          image: ghcr.io/grycap/oscar:3.6.2
          format: cyclonedx-json
          output-file: sbom-oscar-cyclonedx.json

      - name: Run Grype to scan from SBOM
        uses: anchore/scan-action@v3
        with:
          sbom: sbom-oscar-cyclonedx.json
          output-format: table
